Conditional Statements

 - if
 - if,else
 - if, elif,elif,else


In [1]:
#i want find the square if number is greater than 10

In [4]:
num = 9
if num > 10:
    print("Number is ",num)
    print("number is greater than 10")
print("number square is ", num*num)  # not part of if
print("some thing")

number square is  81
some thing


In [7]:
num = 12
if num > 10:
    print("Number is ",num)
    print("number is greater than 10")
    print("number square is ", num*num)  # not part of if
    print("some thing")

Number is  12
number is greater than 10
number square is  144
some thing


In [8]:
#check 2 codition( if else)

# you want to find square is number is even and cube if number is odd

In [17]:
num2 = eval(input("enter a number")) #eval is preserve the data type 
if num2 %2 == 0:
    print("number is even",num2,"its squre is",num2**2)
else:
    print("number is odd", num2,"its cube is",num2**3)

enter a number5
number is odd 5 its cube is 125


In [18]:
# check more than 2 conditionsures 

In [21]:
inflation_rate = int(input("Enter the inflation rate"))

if inflation_rate <= 6:
    print("inflation is with in limits")
    print("nothing to worry")
elif inflation_rate > 6 and inflation_rate < 8:
    print("inflation is very high")
    print("price will increase fast")
    print("govt needs to monitor")
elif inflation_rate >8 and inflation_rate <= 10:
    print("inflation is very very high")
    print("some strict meause are need  by Govt")
    print("RBI alone can not control inflation")
elif inflation_rate >10 and inflation_rate <= 13:
    print("inflation is uncontrolled")
    print("prices of essentials are getting doubled in a year")
else:
    print("govt has totally failed")

Enter the inflation rate5
inflation is with in limits
nothing to worry


In [22]:
# loops -->> for, while loops

In [24]:
i =1
while i<= 50:
    print("Number is  ->>",i,"square is",i*i)
    i=i+1

Number is  ->> 1 square is 1
Number is  ->> 2 square is 4
Number is  ->> 3 square is 9
Number is  ->> 4 square is 16
Number is  ->> 5 square is 25
Number is  ->> 6 square is 36
Number is  ->> 7 square is 49
Number is  ->> 8 square is 64
Number is  ->> 9 square is 81
Number is  ->> 10 square is 100
Number is  ->> 11 square is 121
Number is  ->> 12 square is 144
Number is  ->> 13 square is 169
Number is  ->> 14 square is 196
Number is  ->> 15 square is 225
Number is  ->> 16 square is 256
Number is  ->> 17 square is 289
Number is  ->> 18 square is 324
Number is  ->> 19 square is 361
Number is  ->> 20 square is 400
Number is  ->> 21 square is 441
Number is  ->> 22 square is 484
Number is  ->> 23 square is 529
Number is  ->> 24 square is 576
Number is  ->> 25 square is 625
Number is  ->> 26 square is 676
Number is  ->> 27 square is 729
Number is  ->> 28 square is 784
Number is  ->> 29 square is 841
Number is  ->> 30 square is 900
Number is  ->> 31 square is 961
Number is  ->> 32 square is 1

In [26]:
# for loop --> start from 1st records and wil go till last record
l=[6,6,10,34,3,56,100,67,6,45,4,34,]

# find the square of the nubmers but as soon as a number greater than oe eual to 100 appears stop

In [27]:
for j in l:
    print("Number is  ->>",j,"square is",j*j)
    if j>= 100:
        break

Number is  ->> 6 square is 36
Number is  ->> 6 square is 36
Number is  ->> 10 square is 100
Number is  ->> 34 square is 1156
Number is  ->> 3 square is 9
Number is  ->> 56 square is 3136
Number is  ->> 100 square is 10000


In [46]:
# user defined functions

def add_num(a,b):
    """
    this is addition function,  will return addition
    """
    print("number is",a)
    print("number is",b)
    global result
    result = a+b       # local variable (scope is limited only inside the function)
    return result
    print("tata, bye, bye")

In [47]:
add_num(2,3)

number is 2
number is 3


5

### lambda

In [1]:
#Lambda function --> without name (anounymous function) --- cant have return statement

# how does any function works --> call, execute the logic, give the input

In [2]:
a = lambda a,b,c,d : (a*b*c*d)

# left side input : Right side logic

In [3]:
a(2,3,4,5)

120

### Lambda becomes very powerfull whencombined with map and filter function

### Map()

In [ ]:
# Nature of map to reach and every element

In [4]:
l2 = [2,4,5,6,10,7,8,12]

# u want tofind square of each element in the list

In [6]:
tuple(map(lambda x:x*x,l2))

(4, 16, 25, 36, 100, 49, 64, 144)

## Filter

In [7]:
#filter function (act like some condition)

# find out all the even numbers from l2

list(filter(lambda x:x%2==0,l2))

[2, 4, 6, 10, 8, 12]

## Itertools

In [8]:
import itertools

In [10]:
for j in itertools.count(start=3,step=2):
    print(j)
    if j>25:
        break

3
5
7
9
11
13
15
17
19
21
23
25
27


### itertools

In [11]:
from itertools import product

In [12]:
print(list(product([1,2],repeat = 3)))

[(1, 1, 1), (1, 1, 2), (1, 2, 1), (1, 2, 2), (2, 1, 1), (2, 1, 2), (2, 2, 1), (2, 2, 2)]


In [15]:
print(list(product(['H','T'],repeat = 2)))

[('H', 'H'), ('H', 'T'), ('T', 'H'), ('T', 'T')]


In [16]:
print(list(product([1,2,3,4,5,6],repeat = 2)))

[(1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6), (6, 1), (6, 2), (6, 3), (6, 4), (6, 5), (6, 6)]


In [18]:
print(list(product(['H','T'],repeat = 3)))

[('H', 'H', 'H'), ('H', 'H', 'T'), ('H', 'T', 'H'), ('H', 'T', 'T'), ('T', 'H', 'H'), ('T', 'H', 'T'), ('T', 'T', 'H'), ('T', 'T', 'T')]


In [ ]:
find the probability of getting 4 heads 

In [21]:
l = list(product(['H','T'],repeat = 10))

In [22]:
l

[('H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H'),
 ('H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'T'),
 ('H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'T', 'H'),
 ('H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'T', 'T'),
 ('H', 'H', 'H', 'H', 'H', 'H', 'H', 'T', 'H', 'H'),
 ('H', 'H', 'H', 'H', 'H', 'H', 'H', 'T', 'H', 'T'),
 ('H', 'H', 'H', 'H', 'H', 'H', 'H', 'T', 'T', 'H'),
 ('H', 'H', 'H', 'H', 'H', 'H', 'H', 'T', 'T', 'T'),
 ('H', 'H', 'H', 'H', 'H', 'H', 'T', 'H', 'H', 'H'),
 ('H', 'H', 'H', 'H', 'H', 'H', 'T', 'H', 'H', 'T'),
 ('H', 'H', 'H', 'H', 'H', 'H', 'T', 'H', 'T', 'H'),
 ('H', 'H', 'H', 'H', 'H', 'H', 'T', 'H', 'T', 'T'),
 ('H', 'H', 'H', 'H', 'H', 'H', 'T', 'T', 'H', 'H'),
 ('H', 'H', 'H', 'H', 'H', 'H', 'T', 'T', 'H', 'T'),
 ('H', 'H', 'H', 'H', 'H', 'H', 'T', 'T', 'T', 'H'),
 ('H', 'H', 'H', 'H', 'H', 'H', 'T', 'T', 'T', 'T'),
 ('H', 'H', 'H', 'H', 'H', 'T', 'H', 'H', 'H', 'H'),
 ('H', 'H', 'H', 'H', 'H', 'T', 'H', 'H', 'H', 'T'),
 ('H', 'H', 'H', 'H', 'H', 'T', 'H', 'H', 'T',

In [25]:
l1=[]
for i in l:
    if i.count('H')==4:
        l1.append(i)
        
            

In [27]:
len(l1)

210

In [28]:
len(l1)/len(l)

0.205078125

In [29]:
# a dice is thrown 3 times, find the prob that sum is 9 or more

In [40]:
import numpy as np

In [33]:
l = list(product([1,2,3,4,5,6],repeat = 3))

In [34]:
l

[(1, 1, 1),
 (1, 1, 2),
 (1, 1, 3),
 (1, 1, 4),
 (1, 1, 5),
 (1, 1, 6),
 (1, 2, 1),
 (1, 2, 2),
 (1, 2, 3),
 (1, 2, 4),
 (1, 2, 5),
 (1, 2, 6),
 (1, 3, 1),
 (1, 3, 2),
 (1, 3, 3),
 (1, 3, 4),
 (1, 3, 5),
 (1, 3, 6),
 (1, 4, 1),
 (1, 4, 2),
 (1, 4, 3),
 (1, 4, 4),
 (1, 4, 5),
 (1, 4, 6),
 (1, 5, 1),
 (1, 5, 2),
 (1, 5, 3),
 (1, 5, 4),
 (1, 5, 5),
 (1, 5, 6),
 (1, 6, 1),
 (1, 6, 2),
 (1, 6, 3),
 (1, 6, 4),
 (1, 6, 5),
 (1, 6, 6),
 (2, 1, 1),
 (2, 1, 2),
 (2, 1, 3),
 (2, 1, 4),
 (2, 1, 5),
 (2, 1, 6),
 (2, 2, 1),
 (2, 2, 2),
 (2, 2, 3),
 (2, 2, 4),
 (2, 2, 5),
 (2, 2, 6),
 (2, 3, 1),
 (2, 3, 2),
 (2, 3, 3),
 (2, 3, 4),
 (2, 3, 5),
 (2, 3, 6),
 (2, 4, 1),
 (2, 4, 2),
 (2, 4, 3),
 (2, 4, 4),
 (2, 4, 5),
 (2, 4, 6),
 (2, 5, 1),
 (2, 5, 2),
 (2, 5, 3),
 (2, 5, 4),
 (2, 5, 5),
 (2, 5, 6),
 (2, 6, 1),
 (2, 6, 2),
 (2, 6, 3),
 (2, 6, 4),
 (2, 6, 5),
 (2, 6, 6),
 (3, 1, 1),
 (3, 1, 2),
 (3, 1, 3),
 (3, 1, 4),
 (3, 1, 5),
 (3, 1, 6),
 (3, 2, 1),
 (3, 2, 2),
 (3, 2, 3),
 (3, 2, 4),
 (3, 2, 5),
 (3,

In [44]:
l1 = []
l = list(product([1,2,3,4,5,6], repeat = 3))
for i in l:
    if sum(i) >= 9:
        l1.append(i)
        
len(l1)

TypeError: 'int' object is not callable

In [38]:
t = (1,2,3)
sum = 0
for i in t:
    sum = sum +i
print(sum)

6


In [45]:
from itertools import combinations_with_replacement

In [47]:
list(combinations_with_replacement(['Pune','Mubai','banglore'],2))

[('Pune', 'Pune'),
 ('Pune', 'Mubai'),
 ('Pune', 'banglore'),
 ('Mubai', 'Mubai'),
 ('Mubai', 'banglore'),
 ('banglore', 'banglore')]

In [48]:
Score = np.array([[210, 402, 383],
 [140, 375, 106],
[140, 125, 217],
[292, 240, 295]])

In [49]:
Score

array([[210, 402, 383],
       [140, 375, 106],
       [140, 125, 217],
       [292, 240, 295]])

In [51]:
Score[0].max()

402

In [53]:
for i in Score:
    print(max(i))

402
375
217
295


In [54]:
np.max(Score,axis =1)

array([402, 375, 217, 295])

In [55]:
np.max(Score,axis =0)

array([292, 402, 383])

In [56]:
dates = ['23-10-1993', '12-08-2000','09-12-2021','18-09-2021']

#day,month,year

# want to extract year from ,from each date

In [60]:
for i in dates:
    print(i.split('-')[2])

1993
2000
2021
2021


In [70]:
n = 5
for i in range(0,n):
    for j in range(i+1):
        print("*", end = " ")
    print()

* 
* * 
* * * 
* * * * 
* * * * * 


In [71]:
# sets -->> union, intersection, differrence

### Sets --> is used to represent the unique data in single dim which is ordered and indexing can not be performed on it

In [ ]:
# if we want to remove duplicate pass it into set

In [72]:
#tuple(), list [], dict {}, 

In [75]:
s = set([10,23,20,23,23,4,4,45,56,65,])

In [76]:
s

{4, 10, 20, 23, 45, 56, 65}

In [79]:
prod1 = set(['tv','fridge','ac','bottle','pen','car','mobile','bike'])
prod2 = set(['pen','computer','mobile','fridge','laptop','can','chrger','cup','scoter'])

In [80]:
prod1.union(prod2)

{'ac',
 'bike',
 'bottle',
 'can',
 'car',
 'chrger',
 'computer',
 'cup',
 'fridge',
 'laptop',
 'mobile',
 'pen',
 'scoter',
 'tv'}

In [81]:
prod1.intersection(prod2)

{'fridge', 'mobile', 'pen'}

## find those products which are present in prod1 but not in prod2

In [82]:
prod1.difference(prod2)

{'ac', 'bike', 'bottle', 'car', 'tv'}

In [86]:
prod1 - prod2

{'ac', 'bike', 'bottle', 'car', 'tv'}

## find those products which are present in prod2 but not in prod1

In [83]:
prod2.difference(prod1)

{'can', 'chrger', 'computer', 'cup', 'laptop', 'scoter'}

In [85]:
prod2 - prod1

{'can', 'chrger', 'computer', 'cup', 'laptop', 'scoter'}

In [87]:
prod1.symmetric_difference(prod2)  # removing intersection part

{'ac',
 'bike',
 'bottle',
 'can',
 'car',
 'chrger',
 'computer',
 'cup',
 'laptop',
 'scoter',
 'tv'}

In [90]:
exm_list = [4,10,20 ,11 , 10, 9,3,6,9, 12, 11 ,11, 23]

In [99]:
for i in exm_list:
    if exm_list.count(i)>1:
        print(i)

10
11
10
9
9
11
11
